//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raamen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raman
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Broth { get; set; }
        public string Price { get; set; }
        public int MeatId { get; set; }
    
        public virtual Meat Meat { get; set; }
    }
}
